# Generated by Django 5.1.3 on 2024-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='homework_documents/'),
        ),
    ]
