# Generated by Django 5.1.3 on 2024-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_homework_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='homework_documents/'),
        ),
    ]
