# Generated by Django 5.1.3 on 2024-12-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_homework_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/homework_document/'),
        ),
    ]
