# Generated by Django 5.1.4 on 2025-01-02 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_ebooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
