# Generated by Django 5.1.4 on 2025-01-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_ebooks_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebooks',
            options={'verbose_name': 'Ebooks', 'verbose_name_plural': 'Ebooks'},
        ),
        migrations.RemoveField(
            model_name='ebooks',
            name='title',
        ),
    ]
