# Generated by Django 5.1.4 on 2025-01-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_grouphomework_delete_usertimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouphomework',
            name='is_finished',
        ),
    ]
